# Generated by Django 4.2.4 on 2023-08-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tipoCliente',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.SmallIntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default=1),
        ),
    ]
